name: golangci-lint
on:
  push:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin
     
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run
